import { PlanetName } from './zodiac';

const PLANET_IN_SIGN: Record<PlanetName, Record<number, string>> = {
  Sun: {
    0: 'Bold and pioneering, you lead with courage and a need to express your individuality. Your vitality comes from initiating action.',
    1: 'Steady and sensual, you build lasting value through patience and determination. You find identity in what you create and possess.',
    2: 'Curious and versatile, you express yourself through words, ideas, and constant motion. Variety feeds your sense of self.',
    3: 'Nurturing and emotionally attuned, your identity is rooted in caring for others. You shine when you make people feel safe.',
    4: 'Warm and dramatic, you radiate confidence and creativity. You need to be seen, appreciated, and to lead with heart.',
    5: 'Precise and service-oriented, you find yourself through improvement and mastery of craft. You shine in the details others miss.',
    6: 'Graceful and diplomatic, your identity centers on harmony and relationship. You shine by bringing beauty and balance to any space.',
    7: 'Intense and magnetic, you seek depth and transformation. You live to penetrate beneath surfaces and merge completely.',
    8: 'Expansive and visionary, you seek truth and meaning through adventure. Your identity is tied to freedom and exploration.',
    9: 'Ambitious and disciplined, you build carefully toward mastery and authority. You define yourself through achievement and responsibility.',
    10: 'Independent and unconventional, you define yourself through originality and rebellion against the ordinary. You innovate.',
    11: 'Dreamy and compassionate, your identity dissolves boundaries. You shine through empathy, imagination, and spiritual sensitivity.',
  },
  Moon: {
    0: 'Your emotional needs are immediate and fiery. You react quickly, need independence, and calm through physical action.',
    1: 'Your inner world is steady and comfort-seeking. You need security, beauty, and routine to feel emotionally grounded.',
    2: 'Your feelings shift quickly and are processed through talking. You need variety and mental stimulation to feel settled.',
    3: 'Deeply sensitive and protective, your emotions flow like tides. You need closeness, family, and a sense of belonging.',
    4: 'Warm and generous in feeling, you need to be admired and to express creativity. Pride colors your emotional life.',
    5: 'You process feelings through analysis and usefulness. You feel secure when everything is in order and you are of service.',
    6: 'Your emotions seek balance and partnership. You feel most at peace when relationships are harmonious and beautiful.',
    7: 'Intense and private, your feelings run deep and are rarely shown. You need emotional merging and transformative intimacy.',
    8: 'Restless and optimistic, your moods lift through travel, learning, and freedom. You need meaning to feel emotionally well.',
    9: 'Reserved and responsible, you control your feelings carefully. You need structure and achievement to feel emotionally secure.',
    10: 'Detached and forward-looking, your feelings are processed through intellect. You need freedom and community to feel at home.',
    11: 'Vast and permeable, your emotions absorb everything. You need solitude, art, and spiritual connection to feel whole.',
  },
  Mercury: {
    0: 'Your mind is fast, direct, and pioneering. You decide quickly and communicate with boldness and little patience for delay.',
    1: 'Your thinking is deliberate and practical. You learn through concrete examples and communicate in a steady, measured way.',
    2: 'Quick, curious, and adaptable, you juggle many ideas at once. You communicate with wit, variety, and a love of wordplay.',
    3: 'Your mind is impressionable and memory-driven. You think through feeling and communicate with emotional nuance.',
    4: 'Expressive and creative in thought, you communicate with flair and drama. Your ideas are colored by pride and vision.',
    5: 'Precise, analytical, and detail-oriented, you excel at organizing information. You communicate to be of use and to improve.',
    6: 'Diplomatic and balanced in thought, you weigh every side. You communicate with grace and a desire for fairness.',
    7: 'Penetrating and probing, your mind seeks hidden truths. You communicate with intensity and rarely reveal all you know.',
    8: 'Visionary and broad, your thinking ranges far. You communicate with enthusiasm and a hunger for meaning and truth.',
    9: 'Structured and serious, your mind plans long-term. You communicate carefully, with authority and respect for tradition.',
    10: 'Inventive and objective, you think in breakthroughs. You communicate with originality and a love of the unconventional.',
    11: 'Intuitive and imaginative, your thinking is non-linear. You communicate through image, metaphor, and feeling.',
  },
  Venus: {
    0: 'You love passionately and directly. You fall in love at first sight and value boldness, independence, and adventure in partners.',
    1: 'You love deeply and loyally. You value sensuality, stability, and devotion, and you fall in love through the senses.',
    2: 'You love playfully and intellectually. You value wit, variety, and conversation, and you need mental stimulation in love.',
    3: 'You love tenderly and protectively. You value emotional closeness, family, and a sense of home with your partner.',
    4: 'You love warmly and generously. You value admiration, romance, and grand gestures, and you give with a full heart.',
    5: 'You love through acts of service and devotion. You value reliability, thoughtfulness, and practical care in relationships.',
    6: 'You love harmoniously and gracefully. You value beauty, partnership, and equality, and you seek balance above all.',
    7: 'You love intensely and completely. You value depth, loyalty, and transformative connection, and you give all or nothing.',
    8: 'You love expansively and openly. You value shared adventure, growth, and meaning, and you fall in love with big-hearted optimism.',
    9: 'You love responsibly and with commitment. You value loyalty, patience, and shared goals, and you build love to last.',
    10: 'You love unconventionally and freely. You value friendship, independence, and intellectual connection in romance.',
    11: 'You love compassionately and unconditionally. You value soul connection, tenderness, and a love that transcends boundaries.',
  },
  Mars: {
    0: 'Your drive is direct, bold, and impulsive. You act first and think later, with courage and a competitive spirit.',
    1: 'Your drive is steady and enduring. You pursue goals with patience and determination, and you resist being rushed.',
    2: 'Your drive is scattered and versatile. You pursue many interests at once and act on curiosity and mental energy.',
    3: 'Your drive is indirect and emotionally motivated. You act to protect and nurture, and your energy rises and falls with feeling.',
    4: 'Your drive is dramatic and creative. You act with passion and pride, and you need your efforts to be seen and recognized.',
    5: 'Your drive is precise and service-oriented. You act to fix, improve, and perfect, and you channel energy into craft.',
    6: 'Your drive is diplomatic and relational. You act through cooperation and charm, and you avoid conflict when possible.',
    7: 'Your drive is intense and strategic. You pursue goals with relentless focus, and your willpower is formidable.',
    8: 'Your drive is expansive and adventurous. You act on conviction and enthusiasm, and you pursue freedom and truth.',
    9: 'Your drive is disciplined and ambitious. You pursue goals with patience, strategy, and long-term commitment.',
    10: 'Your drive is unpredictable and innovative. you act on sudden inspiration and resist any constraint on your freedom.',
    11: 'Your drive is subtle and often diffused. You act on inspiration and feeling, and your energy flows best in creative or spiritual pursuits.',
  },
  Jupiter: {
    0: 'You grow through courage, initiative, and adventure. Your faith is bold, and you expand by taking leaps and leading the way.',
    1: 'You grow through patience, sensuality, and building. Your faith is steady, and you expand by accumulating value and beauty.',
    2: 'You grow through learning, communication, and connection. Your faith is curious, and you expand through ideas and exchange.',
    3: 'You grow through caring, family, and emotional depth. Your faith is nurturing, and you expand by making others feel at home.',
    4: 'You grow through creativity, generosity, and self-expression. Your faith is warm, and you expand by shining and inspiring.',
    5: 'You grow through service, mastery, and improvement. Your faith is practical, and you expand by perfecting your craft.',
    6: 'You grow through partnership, beauty, and harmony. Your faith is relational, and you expand through connection and grace.',
    7: 'You grow through depth, transformation, and intensity. Your faith is profound, and you expand by merging and confronting the taboo.',
    8: 'You grow through travel, philosophy, and meaning. Your faith is expansive, and you expand through adventure and truth-seeking.',
    9: 'You grow through discipline, achievement, and responsibility. Your faith is structured, and you expand through mastery and authority.',
    10: 'You grow through innovation, community, and freedom. Your faith is visionary, and you expand by breaking old molds.',
    11: 'You grow through compassion, imagination, and spiritual connection. Your faith is mystical, and you expand by dissolving boundaries.',
  },
  Saturn: {
    0: 'You are disciplined about independence and initiative. You learn responsibility through leadership and face fear by acting anyway.',
    1: 'You are disciplined about resources and values. You learn patience through building slowly and face fear of loss by creating lasting security.',
    2: 'You are disciplined about communication and learning. You face fear of inadequacy by mastering knowledge and speaking with authority.',
    3: 'You are disciplined about emotions and family. You learn responsibility through caring for others and face fear by building emotional foundations.',
    4: 'You are disciplined about self-expression and creativity. You learn responsibility through your work and face fear of being unseen by earning recognition.',
    5: 'You are disciplined about service and health. You face fear of imperfection by refining your craft and taking responsibility for your body and routines.',
    6: 'You are disciplined about partnership and harmony. You learn responsibility through commitment and face fear of conflict by building enduring relationships.',
    7: 'You are disciplined about transformation and intimacy. You face fear of loss and control by embracing vulnerability and deep psychological work.',
    8: 'You are disciplined about meaning and belief. You learn responsibility through long study and face fear of limits by building a solid philosophy.',
    9: 'You are disciplined about ambition and authority. You face fear of failure through sustained effort and earn your place through patience and mastery.',
    10: 'You are disciplined about freedom and community. You learn responsibility through innovation and face fear of conformity by building new structures.',
    11: 'You are disciplined about the unconscious and the hidden. You face fear of chaos through spiritual practice and learn to let go of control.',
  },
  Uranus: {
    0: 'You rebel through bold independence and sudden initiative. You innovate by breaking old patterns of aggression and pioneering new ways to lead.',
    1: 'You rebel through unconventional values and sudden changes in resources. You innovate by redefining what security and beauty mean.',
    2: 'You rebel through radical ideas and new ways of communicating. You innovate by breaking old thought patterns and connecting in novel ways.',
    3: 'You rebel through emotional freedom and unconventional family life. You innovate by redefining home, belonging, and care.',
    4: 'You rebel through creative originality and dramatic self-expression. You innovate by shining in unique, unexpected ways.',
    5: 'You rebel through unconventional methods and new approaches to work and health. You innovate by refining systems in novel ways.',
    6: 'You rebel through unconventional partnerships and sudden changes in relationship. You innovate by redefining balance and harmony.',
    7: 'You rebel through intense transformation and sudden psychological shifts. You innovate by breaking taboos and diving into the forbidden.',
    8: 'You rebel through unconventional beliefs and sudden quests for meaning. You innovate by expanding freedom and seeking new horizons.',
    9: 'You rebel through unconventional ambition and sudden changes in career. You innovate by building new structures and redefining authority.',
    10: 'You rebel through radical community and freedom-oriented friendships. You innovate by envisioning new futures and breaking old molds.',
    11: 'You rebel through spiritual awakening and sudden dissolving of boundaries. You innovate by channeling universal compassion in new ways.',
  },
  Neptune: {
    0: 'You dream of bold new beginnings and idealize the pioneer. You dissolve boundaries through courageous compassion and visionary action.',
    1: 'You dream of perfect beauty and idealize the sensual. You dissolve boundaries through devotion to comfort, art, and lasting value.',
    2: 'You dream of perfect understanding and idealize the mind. You dissolve boundaries through empathic communication and imaginative ideas.',
    3: 'You dream of perfect belonging and idealize home and family. You dissolve boundaries through emotional merging and spiritual nurturing.',
    4: 'You dream of perfect self-expression and idealize the creative. You dissolve boundaries through radiant love and artistic generosity.',
    5: 'You dream of perfect service and idealize the healer. You dissolve boundaries through compassionate craft and devotion to others\u2019 well-being.',
    6: 'You dream of perfect harmony and idealize the beloved. You dissolve boundaries through romantic merging and aesthetic grace.',
    7: 'You dream of total transformation and idealize the soul mate. You dissolve boundaries through profound intimacy and spiritual merging.',
    8: 'You dream of perfect meaning and idealize the seeker. You dissolve boundaries through mystical exploration and universal love.',
    9: 'You dream of perfect achievement and idealize the master. You dissolve boundaries through devotion to a higher calling and spiritual discipline.',
    10: 'You dream of perfect community and idealize the future. You dissolve boundaries through universal friendship and visionary ideals.',
    11: 'You dream of perfect oneness and idealize the divine. You dissolve all boundaries through mystical union and boundless compassion.',
  },
  Pluto: {
    0: 'You transform through bold initiative and the death of old identities. Your power is forged by facing fear and pioneering rebirth.',
    1: 'You transform through resources and values, shedding old attachments. Your power is forged by rebuilding security from the ground up.',
    2: 'You transform through ideas and communication, shedding old mental patterns. Your power is forged by reinventing how you think and connect.',
    3: 'You transform through emotional depths and family patterns. Your power is forged by confronting inherited pain and building new foundations.',
    4: 'You transform through creativity and self-expression, shedding old ego. Your power is forged by dying to pride and being reborn in authentic radiance.',
    5: 'You transform through service and health, shedding old habits. Your power is forged by reinventing your daily craft and relationship to the body.',
    6: 'You transform through partnership and harmony, shedding old relational patterns. Your power is forged by dying to codependence and rebirth in balance.',
    7: 'You transform through total psychological renewal. Your power is forged by confronting the shadow, dying to the old self, and emerging reborn.',
    8: 'You transform through meaning and belief, shedding old philosophies. Your power is forged by reinventing your truth and seeking deeper horizons.',
    9: 'You transform through ambition and authority, shedding old structures. Your power is forged by tearing down and rebuilding your public role.',
    10: 'You transform through community and ideals, shedding old collective patterns. Your power is forged by reinventing the future and leading change.',
    11: 'You transform through the unconscious and the hidden. Your power is forged by confronting deep wounds and emerging with spiritual authority.',
  },
  NorthNode: {
    0: 'Your soul path points toward bold initiative and authentic selfhood. Release over-dependence on others; learn to lead and act independently.',
    1: 'Your soul path points toward building lasting value and honoring your senses. Release restlessness; learn patience, commitment, and self-worth.',
    2: 'Your soul path points toward curiosity, learning, and authentic communication. Release rigid beliefs; learn to stay open and exchange ideas.',
    3: 'Your soul path points toward emotional depth, nurturing, and creating home. Release cold ambition; learn to feel and care for others.',
    4: 'Your soul path points toward creative self-expression and leading from the heart. Release hiding in the crowd; learn to shine and be seen.',
    5: 'Your soul path points toward service, craft, and mindful daily routines. Release grandiosity; learn humility and the sacred in the small.',
    6: 'Your soul path points toward partnership, harmony, and true relationship. Release fierce independence; learn to balance self and other.',
    7: 'Your soul path points toward depth, intimacy, and transformation. Release superficiality; learn to merge and face the shadow.',
    8: 'Your soul path points toward meaning, adventure, and truth-seeking. Release fear of the unknown; learn to explore and expand.',
    9: 'Your soul path points toward responsibility, mastery, and building something lasting. Release fear of failure; learn discipline and commitment.',
    10: 'Your soul path points toward community, freedom, and authentic individuality. Release old traditions; learn to innovate and belong to the future.',
    11: 'Your soul path points toward compassion, surrender, and spiritual connection. Release rigid control; learn to let go and trust the unseen.',
  },
  Chiron: {
    0: 'Your wound is around identity and the right to exist. You heal by embracing your vulnerability and helping others find their courage.',
    1: 'Your wound is around self-worth and having enough. You heal by valuing yourself from within and helping others find their worth.',
    2: 'Your wound is around being heard and understood. You heal by speaking your truth and helping others find their voice.',
    3: 'Your wound is around belonging and emotional safety. You heal by creating inner home and helping others feel they belong.',
    4: 'Your wound is around being seen and valued. You heal by shining authentically and helping others find their creative spark.',
    5: 'Your wound is around usefulness and perfection. You heal by accepting imperfection and helping others feel enough as they are.',
    6: 'Your wound is around relationship and balance. You heal by finding harmony within and helping others relate authentically.',
    7: 'Your wound is around intimacy and trust. You heal by embracing your depths and helping others face their shadows.',
    8: 'Your wound is around meaning and belief. You heal by seeking your own truth and helping others find meaning.',
    9: 'Your wound is around authority and achievement. You heal by defining success on your terms and helping others build with integrity.',
    10: 'Your wound is around belonging and individuality. You heal by embracing your uniqueness and helping others find their tribe.',
    11: 'Your wound is around separation and the illusion of boundaries. You heal by dissolving walls and helping others connect to the divine.',
  },
};

const PLANET_IN_HOUSE: Record<PlanetName, string[]> = {
  Sun: [
    'Your identity shines through your self-presentation and first impressions. You are here to be seen as yourself.',
    'Your sense of self is tied to what you value and earn. You shine by building worth, materially and within.',
    'You express yourself through communication and ideas. You shine by sharing your voice and connecting with your immediate world.',
    'Your identity is rooted in home, family, and inner foundations. You shine by creating a sense of belonging.',
    'You express yourself through creativity, play, and romance. You shine by sharing your heart\u2019s joy.',
    'You find yourself through work, service, and daily craft. You shine by being useful and refining your routines.',
    'Your identity is shaped in partnership. You shine through relationship and the mirror of the other.',
    'You find yourself through depth, intimacy, and transformation. You shine by embracing the hidden and the shared.',
    'You express yourself through philosophy, travel, and the search for meaning. You shine by seeking truth.',
    'Your identity is tied to career and public standing. You shine by achieving and being recognized in the world.',
    'You express yourself through community, friendship, and shared ideals. You shine by leading toward a better future.',
    'You find yourself in solitude, the unconscious, and the hidden. You shine by connecting to the divine and healing the unseen.',
  ],
  Moon: [
    'Your emotional needs show in your first impression. You need to feel authentically yourself to be secure.',
    'You need material security and sensory comfort to feel emotionally grounded.',
    'You process feelings through talking, learning, and connecting with siblings and neighbors.',
    'Home and family are the center of your emotional world. You need a safe base to feel secure.',
    'You need to create, play, and be admired to feel emotionally fulfilled.',
    'You feel secure when your routines are in order and you are of service.',
    'You need harmonious partnership to feel emotionally at peace.',
    'You need deep emotional merging and intimacy to feel secure.',
    'You need meaning, travel, and exploration to feel emotionally alive.',
    'You need achievement and public recognition to feel emotionally secure.',
    'You need community and friendship to feel emotionally at home.',
    'You need solitude, spiritual practice, and time in the unseen to feel whole.',
  ],
  Mercury: [
    'You communicate directly and project your ideas boldly. Your mind is part of your first impression.',
    'You think practically about resources and values. You communicate to build and secure.',
    'Communication is central to your life \u2014 talking, writing, and learning define you.',
    'Your thinking is colored by feeling and memory. You communicate with emotional nuance.',
    'You communicate with flair and creativity. Your ideas are dramatic and expressive.',
    'You think precisely about work, health, and craft. You communicate to improve and serve.',
    'You think in terms of partnership and balance. You communicate to harmonize and relate.',
    'Your mind probes depths and secrets. You communicate with intensity and discretion.',
    'You think about meaning, philosophy, and the big picture. You communicate to explore and teach.',
    'You think strategically about career and reputation. You communicate with authority.',
    'You think about the future, community, and ideals. You communicate to innovate and connect.',
    'Your mind explores the hidden, the spiritual, and the unconscious. You communicate through intuition.',
  ],
  Venus: [
    'You attract through your personal presence and charm. Love and beauty are part of your first impression.',
    'You love through giving and receiving value. You attract by building and savoring.',
    'You fall in love through conversation and shared ideas. You attract with wit and words.',
    'You love through nurturing and creating home. You attract by making others feel safe.',
    'You love through romance and creative play. You attract by shining and expressing joy.',
    'You show love through acts of service. You attract by being thoughtful and reliable.',
    'Love and partnership are central to your life. You attract through harmony and grace.',
    'You love through deep intimacy and merging. You attract with intensity and mystery.',
    'You love through shared adventure and meaning. You attract with enthusiasm and vision.',
    'You love through shared ambition and commitment. You attract with competence and authority.',
    'You love through friendship and shared ideals. You attract with originality and vision.',
    'You love with boundless compassion and tenderness. You attract through spiritual sensitivity.',
  ],
  Mars: [
    'You act boldly and directly. Your drive is visible in your first impression.',
    'You act steadily to build and secure. Your drive is patient and enduring.',
    'You act on curiosity and ideas. Your drive is mental and versatile.',
    'You act to protect and nurture. Your drive is emotional and instinctive.',
    'You act with creative passion and pride. Your drive is dramatic and expressive.',
    'You act to fix, refine, and serve. Your drive is precise and craft-oriented.',
    'You act through cooperation and partnership. Your drive is relational and diplomatic.',
    'You act with intensity and strategic focus. Your drive is transformative and relentless.',
    'You act on conviction and seek adventure. Your drive is expansive and meaning-driven.',
    'You act with ambition and discipline. Your drive is focused on achievement and authority.',
    'You act for the future and the collective. Your drive is innovative and idealistic.',
    'You act on inspiration and intuition. Your drive is subtle and often hidden.',
  ],
  Jupiter: [
    'You grow through bold self-expression and initiative. Opportunity finds you when you lead.',
    'You grow through building value and savoring life. Opportunity finds you through patience.',
    'You grow through learning and communication. Opportunity finds you through ideas.',
    'You grow through family and emotional depth. Opportunity finds you through caring.',
    'You grow through creativity and generosity. Opportunity finds you when you shine.',
    'You grow through service and mastery. Opportunity finds you through craft.',
    'You grow through partnership and harmony. Opportunity finds you through relationship.',
    'You grow through depth and transformation. Opportunity finds you through intimacy.',
    'You grow through travel and philosophy. Opportunity finds you through meaning.',
    'You grow through career and achievement. Opportunity finds you through authority.',
    'You grow through community and ideals. Opportunity finds you through friendship.',
    'You grow through solitude and spirituality. Opportunity finds you through surrender.',
  ],
  Saturn: [
    'You learn responsibility through your self-presentation and identity. Discipline shapes who you become.',
    'You learn responsibility through your resources and values. Discipline builds your security.',
    'You learn responsibility through communication and learning. Discipline sharpens your mind.',
    'You learn responsibility through home and family. Discipline builds your foundation.',
    'You learn responsibility through creativity and self-expression. Discipline refines your art.',
    'You learn responsibility through work and health. Discipline shapes your daily life.',
    'You learn responsibility through partnership. Discipline builds enduring commitment.',
    'You learn responsibility through transformation and intimacy. Discipline deepens your power.',
    'You learn responsibility through philosophy and meaning. Discipline builds your worldview.',
    'You learn responsibility through career and public life. Discipline builds your legacy.',
    'You learn responsibility through community and ideals. Discipline builds your vision.',
    'You learn responsibility through the unconscious and the hidden. Discipline builds your inner temple.',
  ],
  Uranus: [
    'You innovate through your self-presentation. Sudden changes reshape your identity.',
    'You innovate through your values and resources. Sudden changes reshape what you hold dear.',
    'You innovate through communication and ideas. Sudden changes reshape how you think.',
    'You innovate through home and family. Sudden changes reshape your foundations.',
    'You innovate through creativity and play. Sudden changes reshape your expression.',
    'You innovate through work and health. Sudden changes reshape your routines.',
    'You innovate through partnership. Sudden changes reshape your relationships.',
    'You innovate through transformation. Sudden changes reshape your depths.',
    'You innovate through philosophy and travel. Sudden changes reshape your beliefs.',
    'You innovate through career. Sudden changes reshape your public role.',
    'You innovate through community and friendship. Sudden changes reshape your ideals.',
    'You innovate through the unconscious. Sudden changes reshape your inner world.',
  ],
  Neptune: [
    'You dissolve boundaries around your identity. You idealize selfhood and may blur your sense of self.',
    'You dissolve boundaries around your values. You idealize beauty and may blur your sense of worth.',
    'You dissolve boundaries around your mind. You idealize ideas and may blur your thinking.',
    'You dissolve boundaries around home and family. You idealize belonging and may blur your roots.',
    'You dissolve boundaries around creativity. You idealize self-expression and may blur your ego.',
    'You dissolve boundaries around work and health. You idealize service and may blur your limits.',
    'You dissolve boundaries around partnership. You idealize love and may blur your relationships.',
    'You dissolve boundaries around intimacy. You idealize merging and may blur your depths.',
    'You dissolve boundaries around meaning. You idealize truth and may blur your beliefs.',
    'You dissolve boundaries around career. You idealize vocation and may blur your ambition.',
    'You dissolve boundaries around community. You idealize friendship and may blur your ideals.',
    'You dissolve boundaries around the unconscious. You idealize the divine and may blur your soul.',
  ],
  Pluto: [
    'You transform through your identity. Power and rebirth shape who you become.',
    'You transform through your values and resources. Power and rebirth reshape what you hold.',
    'You transform through communication. Power and rebirth reshape your ideas.',
    'You transform through home and family. Power and rebirth reshape your foundations.',
    'You transform through creativity. Power and rebirth reshape your self-expression.',
    'You transform through work and health. Power and rebirth reshape your routines.',
    'You transform through partnership. Power and rebirth reshape your relationships.',
    'You transform through intimacy. Power and rebirth reshape your depths.',
    'You transform through philosophy. Power and rebirth reshape your beliefs.',
    'You transform through career. Power and rebirth reshape your public role.',
    'You transform through community. Power and rebirth reshape your ideals.',
    'You transform through the unconscious. Power and rebirth reshape your soul.',
  ],
  NorthNode: [
    'Your soul path is about authentic selfhood. You are learning to lead and be yourself.',
    'Your soul path is about building worth. You are learning patience and self-value.',
    'Your soul path is about learning and communication. You are learning to stay open.',
    'Your soul path is about home and feeling. You are learning to care and belong.',
    'Your soul path is about creative self-expression. You are learning to shine.',
    'Your soul path is about service and craft. You are learning humility and usefulness.',
    'Your soul path is about partnership. You are learning to balance self and other.',
    'Your soul path is about intimacy and transformation. You are learning to merge.',
    'Your soul path is about meaning and adventure. You are learning to explore.',
    'Your soul path is about responsibility and achievement. You are learning discipline.',
    'Your soul path is about community and ideals. You are learning to belong to the future.',
    'Your soul path is about surrender and the unseen. You are learning to let go.',
  ],
  Chiron: [
    'Your wound and healing gift are around identity and selfhood.',
    'Your wound and healing gift are around self-worth and resources.',
    'Your wound and healing gift are around communication and being heard.',
    'Your wound and healing gift are around home, family, and belonging.',
    'Your wound and healing gift are around creativity and being seen.',
    'Your wound and healing gift are around work, health, and usefulness.',
    'Your wound and healing gift are around partnership and relationship.',
    'Your wound and healing gift are around intimacy and transformation.',
    'Your wound and healing gift are around meaning and belief.',
    'Your wound and healing gift are around authority and public role.',
    'Your wound and healing gift are around community and belonging.',
    'Your wound and healing gift are around the unconscious and the divine.',
  ],
};

export function getPlanetInSign(planet: PlanetName, sign: number): string {
  return PLANET_IN_SIGN[planet][sign] ?? '';
}

export function getPlanetInHouse(planet: PlanetName, house: number): string {
  return PLANET_IN_HOUSE[planet][house - 1] ?? '';
}

export function getRisingDescription(sign: number): string {
  const descriptions = [
    'You come across as bold, direct, and energetic. Your presence is pioneering and people sense your initiative immediately.',
    'You come across as steady, grounded, and sensual. Your presence is calm and people sense your reliability.',
    'You come across as curious, quick, and lively. Your presence is mercurial and people sense your wit.',
    'You come across as nurturing, sensitive, and protective. Your presence is warm and people feel safe with you.',
    'You come across as confident, warm, and dramatic. Your presence is radiant and people are drawn to your light.',
    'You come across as precise, thoughtful, and helpful. Your presence is modest and people sense your care.',
    'You come across as graceful, diplomatic, and charming. Your presence is harmonious and people sense your balance.',
    'You come across as intense, magnetic, and private. Your presence is powerful and people sense your depth.',
    'You come across as optimistic, adventurous, and free. Your presence is expansive and people sense your vision.',
    'You come across as serious, ambitious, and capable. Your presence is steady and people sense your authority.',
    'You come across as unique, friendly, and detached. Your presence is unconventional and people sense your originality.',
    'You come across as dreamy, compassionate, and otherworldly. Your presence is gentle and people sense your depth of soul.',
  ];
  return descriptions[sign] ?? '';
}

export function getAspectDescription(aspectName: string, planetA: PlanetName, planetB: PlanetName): string {
  const energyA: Record<PlanetName, string> = {
    Sun: 'identity and vitality',
    Moon: 'emotions and instincts',
    Mercury: 'mind and communication',
    Venus: 'love and values',
    Mars: 'drive and action',
    Jupiter: 'expansion and faith',
    Saturn: 'structure and discipline',
    Uranus: 'innovation and freedom',
    Neptune: 'dreams and spirituality',
    Pluto: 'transformation and power',
    NorthNode: 'soul direction',
    Chiron: 'wounding and healing',
  };
  const a = energyA[planetA];
  const b = energyA[planetB];

  switch (aspectName) {
    case 'Conjunction':
      return `Your ${a} and ${b} are fused, intensifying each other. This is a core dynamic of your chart.`;
    case 'Opposition':
      return `Your ${a} and ${b} are in tension, pulling you in two directions. Awareness and integration are your path.`;
    case 'Trine':
      return `Your ${a} and ${b} flow together with ease, a natural gift that supports you.`;
    case 'Square':
      return `Your ${a} and ${b} create friction, driving growth through challenge. This tension makes you stronger.`;
    case 'Sextile':
      return `Your ${a} and ${b} create opportunity. With a little effort, they cooperate well.`;
    case 'Quincunx':
      return `Your ${a} and ${b} sit at an awkward angle, requiring constant adjustment.`;
    default:
      return '';
  }
}
